spring:
  profiles:
    active: local
  data:
    mongodb:
        uri: mongodb://hackers:hackers@pmw.iptime.org:9002/
  redis:
    entinel:
      master:
      nodes:
    host: pmw.iptime.org
    port: 22
    database: 1
    password:
      pool:
        max-wait: -1
        max-active: -1
        max-idle: -1
        min-idle: 16
  session:
    store-type: none
start-class: com.rival.hs.SpringMvcApplication